services:
  postgresql:
    image: postgres
    container_name: postgres-shop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
    ports:
      - 15432:5432