services:
  postgresql:
    image: postgres
    container_name: postgres-product-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_service_db
    ports:
      - 15432:5432